#!/usr/bin/env bash
#
# Adds the last 5 commit msg as a reference
# http://codeinthehole.com/writing/enhancing-your-git-commit-editor/
#

BRANCH_NAME=$(git branch | grep '*' | sed 's/* //')
if [ $BRANCH_NAME != '(no branch)' ]
then
 echo "#"
    echo "# Last 5 commit messages" >> $1
    echo "# ----------------------" >> $1
    COMMITS=`git log --pretty=format:"# %h %s [%an]" -5`
    echo "${COMMITS}" >> $1
fi
